# apiVersion: backstage.io/v1alpha1
# kind: API
# metadata:
#   name: OpenAPI
#   description: Open API
# spec:
#   type: openapi
#   lifecycle: production
#   owner: 'team'
#   definition:
#     $openapi: https://petstore3.swagger.io/api/v3/openapi.yaml


apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: apis-guru
  description: The apis.guru REST API
spec:
  type: openapi
  lifecycle: production
  owner: user:guest
  definition:
    $yaml: https://apis.guru/v2/openapi.yaml